name: AprilsFlowers
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07196
title: "Flowers are my passion, they make me relax when I can't get to a beach."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eeeced'
    - '#c3bebb'
    - '#282320'
    - '#59514e'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
