name: AprilsFlowers
favicon: null
layout_spectrum: 0.06617701100185513
typography_spectrum: 0.9983801504131407
title: "Flowers are my passion, they make me relax when I can't get to a beach."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5807853671722114
  lightness: 0.7385876637417823
  saturation: 0.873039681930095
  rhythmicContrast: 0.9632365910802037
purpose: []
